In [29]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [30]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [31]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [32]:
df = df[df['species'] != 'virginica']

In [33]:
df['species'].unique()

array(['setosa', 'versicolor'], dtype=object)

In [34]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [35]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [36]:
# df['species'] = df['species'].map({
#     'versicolor' : 1,
#     'setosa' : 0
# })
# df.head()

In [37]:
from sklearn.preprocessing import LabelEncoder

Label_Encoder = {}

le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])

Label_Encoder["species"] = le

df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [38]:
le.classes_

array(['setosa', 'versicolor'], dtype=object)

In [39]:
# spliting data into X and y 
# dependent and independent variables

X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [40]:
X

    sepal_length  sepal_width  petal_length  petal_width
0            5.1          3.5           1.4          0.2
1            4.9          3.0           1.4          0.2
2            4.7          3.2           1.3          0.2
3            4.6          3.1           1.5          0.2
4            5.0          3.6           1.4          0.2
..           ...          ...           ...          ...
95           5.7          3.0           4.2          1.2
96           5.7          2.9           4.2          1.3
97           6.2          2.9           4.3          1.3
98           5.1          2.5           3.0          1.1
99           5.7          2.8           4.1          1.3

[100 rows x 4 columns]

In [41]:
y

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: species, Length: 100, dtype: int64

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, train_size= 0.8, random_state=42)

In [43]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

In [46]:
from sklearn.model_selection import GridSearchCV
parameter={
    'penalty': ['l1','l2','elasticent'],
    'C': [1,2,3,4,5,6,7,8,12,10,20,30],
    'max_iter': [100,200,300]
}

In [47]:
classifierRegressor = GridSearchCV(lr,param_grid=parameter,scoring='accuracy',cv=5)
classifierRegressor.fit(X_train,y_train)

c:\Users\M.Qasim\miniconda3\envs\python_ml\lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
360 fits failed out of a total of 540.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
180 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\M.Qasim\miniconda3\envs\python_ml\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\M.Qasim\miniconda3\envs\python_ml\lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\M.Qasim\miniconda3\envs\python_ml\lib\site-packages\sklearn\linear_model\_logistic.py", line 1218, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "c:\Users\M.Qasim\miniconda3\envs\python_ml\lib\site-packages\sklearn\linear_model\_logistic.py", line 64, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
180 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\M.Qasim\miniconda3\envs\python_ml\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\M.Qasim\miniconda3\envs\python_ml\lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "c:\Users\M.Qasim\miniconda3\envs\python_ml\lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\M.Qasim\miniconda3\envs\python_ml\lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'elasticnet', 'l2', 'l1'} or None. Got 'elasticent' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\M.Qasim\miniconda3\envs\python_ml\lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [nan  1. nan nan  1. nan nan  1. nan nan  1. nan nan  1. nan nan  1. nan
 nan  1. nan nan  1. nan nan  1. nan nan  1. nan nan  1. nan nan  1. nan
 nan  1. nan nan  1. nan nan  1. nan nan  1. nan nan  1. nan nan  1. nan
 nan  1. nan nan  1. nan nan  1. nan nan  1. nan nan  1. nan nan  1. nan
 nan  1. nan nan  1. nan nan  1. nan nan  1. nan nan  1. nan nan  1. nan
 nan  1. nan nan  1. nan nan  1. nan nan  1. nan nan  1. nan nan  1. nan]
  warnings.warn(

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 4, 5, 6, 7, 8, 12, 10, 20, 30],
                         'max_iter': [100, 200, 300],
                         'penalty': ['l1', 'l2', 'elasticent']},
             scoring='accuracy')

In [52]:
classifierRegressor.best_params_

{'C': 1, 'max_iter': 100, 'penalty': 'l2'}

In [58]:
print(classifierRegressor.best_score_)

1.0

In [64]:
y_pred = classifierRegressor.predict(X_test)

In [67]:
from sklearn.metrics import accuracy_score,f1_score,classification_report

print(f'Accuracy Score is: {accuracy_score(y_pred,y_test)}')
print(f'f1 score is: {f1_score(y_pred,y_test)}')

Accuracy Score is: 1.0
f1 score is: 1.0

In [69]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

In [93]:
# predict on anonomus dataset
classifierRegressor.predict([[6,5,15,0.2]])

c:\Users\M.Qasim\miniconda3\envs\python_ml\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])

In [94]:
classifierRegressor.predict([[6,5,1,0.2]])

c:\Users\M.Qasim\miniconda3\envs\python_ml\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])